services:
  db:
    container_name: db
    image: postgres:18.3
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB__POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB__POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB__POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - internal

  reservium-api:
    container_name: reservation-backend
    build:
      context: .
      dockerfile: Dockerfile
#    image: reservationbuk/reservation-backend:latest
    environment:
      ORGANIZATION_NAME: "Buben Club"

      DB__POSTGRES_USER: ${DB__POSTGRES_USER}
      DB__POSTGRES_PASSWORD: ${DB__POSTGRES_PASSWORD}
      DB__POSTGRES_DB: ${DB__POSTGRES_DB}
      DB__POSTGRES_SERVER: db

      MAIL__USERNAME: ${MAIL__USERNAME}
      MAIL__PASSWORD: ${MAIL__PASSWORD}
      MAIL__FROM_NAME: ${MAIL__FROM_NAME}
      MAIL__SENT_DORMITORY_HEAD: true
      MAIL__DORMITORY_HEAD_EMAIL: develop@buk.cvut.cz

      KEYCLOAK__SERVER_URL: ${KEYCLOAK__SERVER_URL}
      KEYCLOAK__REALM: ${KEYCLOAK__REALM}
      KEYCLOAK__CLIENT_ID: ${KEYCLOAK__CLIENT_ID}
      KEYCLOAK__CLIENT_SECRET: ${KEYCLOAK__CLIENT_SECRET}

      GOOGLE__PROJECT_ID: ${GOOGLE__PROJECT_ID}
      GOOGLE__PRIVATE_KEY_ID: ${GOOGLE__PRIVATE_KEY_ID}
      GOOGLE__PRIVATE_KEY: ${GOOGLE__PRIVATE_KEY}
      GOOGLE__CLIENT_EMAIL: ${GOOGLE__CLIENT_EMAIL}
      GOOGLE__CLIENT_ID: ${GOOGLE__CLIENT_ID}
      GOOGLE__CLIENT_X509_CERT_URL: ${GOOGLE__CLIENT_X509_CERT_URL}
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./reservation-app/src:/usr/src/app/src
    ports:
      - "8000:8000"
    networks:
      - internal
    
  # reservium-ui:
  #   container_name: reservium-ui
  #   image: darkrader/reservium-ui:latest-dev
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - internal

networks:
  internal:

volumes:
  postgres_data: