name: buk-reservation
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi=0.95.1
  - uvicorn=0.21.1
  - websockets=10.4
  - jinja2=3.1.2
  - pylint=2.17.1
  - pandas=2.0.0
  - passlib=1.7.4
  - pytest=7.2.2
  - sqlalchemy=2.0.8
  - psycopg2=2.9.3
  - python-dotenv=1.0.0
  - python-jose=3.3.0
  - python-multipart=0.0.6
  - duckdb-engine=0.7.0
  - mypy=1.2.0
  - conda-pack=0.7.0
  - conda-lock=1.4.0
platforms:
  - linux-64
  - win-64
  - osx-arm64

