"""unique false in name mini service

Revision ID: 9cde93d7ffff
Revises: e30e75ce9be2
Create Date: 2025-07-06 18:10:32.248171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cde93d7ffff"
down_revision: Union[str, None] = "e30e75ce9be2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("mini_service_name_key"), "mini_service", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("mini_service_name_key"),
        "mini_service",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
