"""Delete Room Number in User Atribute

Revision ID: b9460f13374f
Revises: 13b00231d2ee
Create Date: 2025-09-28 13:42:08.012483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9460f13374f"
down_revision: Union[str, None] = "13b00231d2ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "room_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("room_number", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
