"""Add Created and Updated At Base Model

Revision ID: c3ebf15d446c
Revises: 6c51860b9a00
Create Date: 2026-04-29 23:41:23.387419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3ebf15d446c"
down_revision: Union[str, None] = "6c51860b9a00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar_collision_associations",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "calendar_collision_associations",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "calendar_collision_associations",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "calendar_mini_service_associations",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "calendar_mini_service_associations",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "calendar_mini_service_associations",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "calendars",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("calendars", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "events",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("events", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "mini_services",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "mini_services", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "reservation_services",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "reservation_services", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("reservation_services", "updated_at")
    op.drop_column("reservation_services", "created_at")
    op.drop_column("mini_services", "updated_at")
    op.drop_column("mini_services", "created_at")
    op.drop_column("events", "updated_at")
    op.drop_column("events", "created_at")
    op.drop_column("calendars", "updated_at")
    op.drop_column("calendars", "created_at")
    op.drop_column("calendar_mini_service_associations", "deleted_at")
    op.drop_column("calendar_mini_service_associations", "updated_at")
    op.drop_column("calendar_mini_service_associations", "created_at")
    op.drop_column("calendar_collision_associations", "deleted_at")
    op.drop_column("calendar_collision_associations", "updated_at")
    op.drop_column("calendar_collision_associations", "created_at")
    # ### end Alembic commands ###
