"""Fix Constraints

Revision ID: 3968aba1a120
Revises: aa608d47ad1f
Create Date: 2026-04-25 12:09:22.074153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3968aba1a120"
down_revision: Union[str, None] = "aa608d47ad1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_calendar_collision_association_calendar_id_collides_with_id"),
        "calendar_collision_associations",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_calendar_collision_associations_calendar_id_collides_with_id"),
        "calendar_collision_associations",
        ["calendar_id", "collides_with_id"],
    )
    op.drop_constraint(
        op.f("uq_calendar_mini_service_association_calendar_id_mini_s_85d8"),
        "calendar_mini_service_associations",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_calendar_mini_service_associations_calendar_id_mini_service_id"),
        "calendar_mini_service_associations",
        ["calendar_id", "mini_service_id"],
    )
    op.drop_constraint(op.f("uq_calendar_reservation_type"), "calendars", type_="unique")
    op.create_unique_constraint(
        op.f("uq_calendars_reservation_type"), "calendars", ["reservation_type"]
    )
    op.drop_constraint(op.f("uq_reservation_service_alias"), "reservation_services", type_="unique")
    op.drop_constraint(op.f("uq_reservation_service_name"), "reservation_services", type_="unique")
    op.create_unique_constraint(
        op.f("uq_reservation_services_alias"), "reservation_services", ["alias"]
    )
    op.create_unique_constraint(
        op.f("uq_reservation_services_name"), "reservation_services", ["name"]
    )
    op.drop_constraint(op.f("uq_user_username"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_username"), "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("uq_user_username"), "users", ["username"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint(op.f("uq_reservation_services_name"), "reservation_services", type_="unique")
    op.drop_constraint(
        op.f("uq_reservation_services_alias"), "reservation_services", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_reservation_service_name"),
        "reservation_services",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_reservation_service_alias"),
        "reservation_services",
        ["alias"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("uq_calendars_reservation_type"), "calendars", type_="unique")
    op.create_unique_constraint(
        op.f("uq_calendar_reservation_type"),
        "calendars",
        ["reservation_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(
        op.f("uq_calendar_mini_service_associations_calendar_id_mini_service_id"),
        "calendar_mini_service_associations",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_calendar_mini_service_association_calendar_id_mini_s_85d8"),
        "calendar_mini_service_associations",
        ["calendar_id", "mini_service_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(
        op.f("uq_calendar_collision_associations_calendar_id_collides_with_id"),
        "calendar_collision_associations",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_calendar_collision_association_calendar_id_collides_with_id"),
        "calendar_collision_associations",
        ["calendar_id", "collides_with_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
