"""Remove head_section Column from User

Revision ID: 6c51860b9a00
Revises: 3968aba1a120
Create Date: 2026-04-25 21:05:29.791521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c51860b9a00"
down_revision: Union[str, None] = "3968aba1a120"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "section_head")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("section_head", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
