"""Add Collision Association Relationship

Revision ID: 13b00231d2ee
Revises: 19f56c4f5a2b
Create Date: 2025-09-11 18:28:55.921772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13b00231d2ee"
down_revision: Union[str, None] = "19f56c4f5a2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_collision_association",
        sa.Column("calendar_id", sa.String(), nullable=False),
        sa.Column("collides_with_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendar.id"],
            name=op.f("fk_calendar_collision_association_calendar_id_calendar"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collides_with_id"],
            ["calendar.id"],
            name=op.f("fk_calendar_collision_association_collides_with_id_calendar"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_collision_association")),
        sa.UniqueConstraint(
            "calendar_id",
            "collides_with_id",
            name=op.f("uq_calendar_collision_association_calendar_id_collides_with_id"),
        ),
    )
    op.drop_column("calendar", "collision_with_calendar")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar",
        sa.Column(
            "collision_with_calendar",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("calendar_collision_association")
    # ### end Alembic commands ###
