"""Remove Deprecated Attrs in Service and Mini Service

Revision ID: f079343cf7ed
Revises: 59e8aba1a121
Create Date: 2026-07-19 22:29:33.272509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f079343cf7ed"
down_revision: Union[str, None] = "59e8aba1a121"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mini_services", "lockers_id")
    op.drop_column("mini_services", "access_group")
    op.drop_column("mini_services", "room_id")
    op.drop_column("reservation_services", "lockers_id")
    op.drop_column("reservation_services", "access_group")
    op.drop_column("reservation_services", "room_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation_services",
        sa.Column("room_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reservation_services",
        sa.Column("access_group", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reservation_services",
        sa.Column(
            "lockers_id", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "mini_services", sa.Column("room_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mini_services", sa.Column("access_group", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "mini_services",
        sa.Column(
            "lockers_id", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
