[pytest]
pythonpath = [ "src" ]
testpaths = ["tests"]
env =
    ORGANIZATION_NAME=Test Organisation

    DB__POSTGRES_USER=devtest
    DB__POSTGRES_PASSWORD=passtest
    DB__POSTGRES_DB=devdbtest

    MAIL__USERNAME=test.user@example.com
    MAIL__PASSWORD=email_pass_test
    MAIL__FROM_NAME=Test Reservium

    OPENID__CLIENT_NAME=openid
    OPENID__CLIENT_ID=test_openid_id
    OPENID__CLIENT_SECRET=test_openid_secret
    OPENID__AUTH_URL=http://openid.test.com/auth
    OPENID__TOKEN_URL=http://openid.test.com/token
    OPENID__METADATA_URL=http://openid.test.com/.well-known/openid-configuration

    GOOGLE__PROJECT_ID=test_google_project_id
    GOOGLE__PRIVATE_KEY_ID=test_google_private_key_id
    GOOGLE__PRIVATE_KEY=test_google_private_key
    GOOGLE__CLIENT_EMAIL=test_google_client_email
    GOOGLE__CLIENT_ID=test_google_client_id
    GOOGLE__CLIENT_X509_CERT_URL=test_google_client_x509_cert_url
